version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: '-'
    groups:
      all-non-major-updates:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
