name: Sync from Retypeset template

concurrency: { group: template-sync, cancel-in-progress: false }

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: radishzzz/astro-theme-retypeset
          upstream_branch: master
          pr_branch_name_prefix: "chore/template_sync"
          pr_title: "chore: sync from upstream theme"
          pr_labels: "template_sync"
          is_pr_cleanup: true
